# Generated by Django 3.0.4 on 2020-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('Created_at', models.DateTimeField(editable=False)),
                ('expire_at', models.DateField()),
                ('Company_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-Created_at'],
            },
        ),
    ]
