# Generated by Django 3.0.4 on 2020-06-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={},
        ),
    ]
