# Generated by Django 3.0.4 on 2020-06-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expires', '0002_auto_20200613_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ['-Created_at']},
        ),
    ]
